#!/usr/bin/env python3
"""Generate src/kanatype/keytable.py from the INSTALLED kmk/keys.py.

KMK has no list of its own keycodes. Keys are built on demand: KC.<NAME> walks
KEY_GENERATORS, and each maybe_make_* function tests the name against a table
of its own -- a local variable inside the function body, so nothing is
importable. A macro picker needs the list, so we extract it.

Extraction rule (ast, not a text scan): inside every maybe_make_* function,
find an assignment whose value is a tuple of (int, (name, alias, ...)) pairs.
That single shape covers ascii, F-keys, nav, numpad and shifted keys. Letters
and digits come from the module-level ALL_ALPHAS / ALL_NUMBER_ALIASES.

Generating from the installed library (rather than typing a list by hand)
means every name we offer is guaranteed to resolve on THIS device.

Usage:
  python gen_keytable.py [path/to/kmk/keys.py] [--out ../src/kanatype/keytable.py]
Default source is the CIRCUITPY drive's lib/kmk/keys.py.
"""
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "..", "src", "kanatype", "keytable.py")

# Which maybe_make_* functions to harvest, and the category each becomes.
# Modifiers are deliberately absent: they are TOGGLES on a macro, not base
# keys, and are handled by kanatype.macros.MOD_BITS.
CATEGORIES = (
    ("maybe_make_more_ascii", "ASCII"),
    ("maybe_make_fn_key", "Fn"),
    ("maybe_make_navlock_key", "Nav"),
    ("maybe_make_numpad_key", "Numpad"),
    ("maybe_make_shifted_key", "Shifted"),
)

# Names that are useless or actively dangerous on a macro key.
SKIP = {"NO", "TRANSPARENT", "TRNS", "RESET", "BOOTLOADER", "DEBUG"}


def find_default_source():
    for drive in "LDEFGHIJKMNOPQRSTUVWXYZ":
        p = "%s:/lib/kmk/keys.py" % drive
        if os.path.exists(p):
            return p
    return None


def literal_names(node):
    """(code, names) pairs from a tuple-of-(int, tuple-of-str) literal."""
    out = []
    if not isinstance(node, (ast.Tuple, ast.List)):
        return out
    for elt in node.elts:
        if not isinstance(elt, (ast.Tuple, ast.List)) or len(elt.elts) != 2:
            return []
        code_node, names_node = elt.elts
        # int for HID codes; str for the shifted keys, whose "code" is the
        # unshifted character (they are ModifiedKey(LSFT, that char)).
        if not isinstance(code_node, (ast.Num, ast.Str)):
            return []
        if not isinstance(names_node, (ast.Tuple, ast.List)):
            return []
        names = []
        for n in names_node.elts:
            if not isinstance(n, ast.Str):
                return []
            names.append(n.s)
        code = code_node.s if isinstance(code_node, ast.Str) else code_node.n
        out.append((code, tuple(names)))
    return out


def display_name(names):
    """Shortest plain-ASCII alias -- the panel is 32 characters wide."""
    plain = [n for n in names
             if len(n) >= 2 and all(c.isalnum() or c == "_" for c in n)]
    return min(plain, key=len) if plain else names[0]


def harvest(path):
    tree = ast.parse(open(path, encoding="utf-8").read(), path)
    funcs = {n.name: n for n in ast.walk(tree)
             if isinstance(n, ast.FunctionDef)}

    rows = []          # (category, primary, display)
    for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        rows.append(("Letters", letter, letter))
    for digit in "1234567890":
        rows.append(("Digits", "N" + digit, digit))

    for fname, category in CATEGORIES:
        fn = funcs.get(fname)
        if fn is None:
            print("  warn: %s not found in %s" % (fname, path))
            continue
        found = []
        for node in ast.walk(fn):
            if isinstance(node, ast.Assign):
                pairs = literal_names(node.value)
                if pairs:
                    found = pairs
                    break
        if not found:
            print("  warn: no key table inside %s" % fname)
            continue
        for _code, names in found:
            if names[0] in SKIP:
                continue
            rows.append((category, names[0], display_name(names)))
    return rows


def table_hash(rows):
    """Cheap 16-bit checksum. Stored beside saved macros so a regenerated
    table invalidates them instead of silently decoding to the wrong key."""
    h = 0
    for _cat, primary, _disp in rows:
        for ch in primary:
            h = (h * 31 + ord(ch)) & 0xFFFF
    return h


def emit(rows, out_path, source):
    cats = []
    for cat, _p, _d in rows:
        if cat not in cats:
            cats.append(cat)
    lines = [
        '"""KMK keycode table -- GENERATED by tools/gen_keytable.py. Do not edit.',
        "",
        "Source: %s" % os.path.basename(source),
        "",
        "KMK builds keys on demand from a name and keeps no list of its own, so",
        "this is extracted from the installed library at build time. NAMES feed",
        "getattr(KC, name); SHORT is what the 128px panel shows; CAT groups them",
        "for browsing. Saved macros store an INDEX into NAMES, guarded by HASH.",
        '"""',
        "",
        "HASH = 0x%04X" % table_hash(rows),
        "",
        "CATEGORIES = (",
    ]
    for c in cats:
        lines.append("    %r," % c)
    lines.append(")")
    lines.append("")
    lines.append("# (category index, KC name, display name)")
    lines.append("NAMES = (")
    for _cat, primary, _disp in rows:
        lines.append("    %r," % primary)
    lines.append(")")
    lines.append("")
    lines.append("SHORT = (")
    for _cat, _primary, disp in rows:
        lines.append("    %r," % disp)
    lines.append(")")
    lines.append("")
    lines.append("CAT = (")
    for cat, _p, _d in rows:
        lines.append("    %d," % cats.index(cat))
    lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("def find(prefix):")
    lines.append('    """Indices whose display name contains `prefix`'
                 ' (case-insensitive)."""')
    lines.append("    p = prefix.upper()")
    lines.append("    if not p:")
    lines.append("        return list(range(len(NAMES)))")
    lines.append("    hits = [i for i, s in enumerate(SHORT) if s.startswith(p)]")
    lines.append("    hits += [i for i, s in enumerate(SHORT)")
    lines.append("             if p in s and not s.startswith(p)]")
    lines.append("    return hits")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def main(argv):
    out = DEFAULT_OUT
    args = []
    i = 0
    while i < len(argv):
        if argv[i] == "--out":
            out = argv[i + 1]
            i += 2
        else:
            args.append(argv[i])
            i += 1
    source = args[0] if args else find_default_source()
    if not source or not os.path.exists(source):
        raise SystemExit(
            "kmk/keys.py not found - plug the device in, or pass the path")
    rows = harvest(source)
    emit(rows, out, source)
    cats = {}
    for cat, _p, _d in rows:
        cats[cat] = cats.get(cat, 0) + 1
    print("%d keys from %s" % (len(rows), source))
    for cat in cats:
        print("  %-8s %d" % (cat, cats[cat]))
    print("-> %s  (hash 0x%04X)" % (os.path.normpath(out), table_hash(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
